platform :ios, '9.0'
use_frameworks!

target 'RADToolKit_Example' do
  pod 'RADToolKit', :path => '../'

  target 'RADToolKit_Tests' do
      inherit! :search_paths

      pod 'RADToolKit', :path => '../'

      pod 'Quick'
      pod 'Nimble'
      pod 'FBSnapshotTestCase'
      pod 'Nimble-Snapshots'
  end
end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['SWIFT_VERSION'] = '2.3'
#        end
#    end
#end

