platform :ios, '9.0'
use_frameworks!

target 'RADToolKit_Example' do
  pod 'RADToolKit', :path => '../'

  target 'RADToolKit_Tests' do
      inherit! :search_paths

      pod 'RADToolKit', :path => '../'

      pod 'Quick'
      pod 'Nimble'
  end
end

post_install do |options|
    options.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
#            swift4_blacklist = []
#            product_name = config.build_settings['PRODUCT_NAME']
#            config.build_settings['SWIFT_VERSION'] = '3.2' if swift4_blacklist.include? product_name
            if config.name == "Release"
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
                else
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
            end
        end
    end
end
